# Generated by Django 4.0.5 on 2022-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('team', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('uniform_number', models.IntegerField()),
            ],
        ),
    ]
