# Generated by Django 4.0.5 on 2022-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restFrameworkTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayer',
            name='profile_img',
            field=models.ImageField(default=1, upload_to='media/<django.db.models.fields.CharField>/'),
            preserve_default=False,
        ),
    ]
