# Generated by Django 4.0.5 on 2022-07-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restFrameworkTest', '0003_alter_footballplayer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballplayer',
            name='profile_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
