# Generated by Django 4.0.5 on 2022-08-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restFrameworkTest', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
